Hypebeast\WordpressBundle\Entity\CommentMeta:
  type: entity
  table: wp_commentmeta
  id:
    meta_id:
      type: bigint
      length: 20
      nullable: false
      generator: { strategy: AUTO }
  fields:
    meta_key:
      type: string
      length: 255
      nullable: true
    meta_value:
      type: text
      nullable: true
  manyToOne:
    comment:
      targetEntity: Comment
      inversedBy: metas
      joinColumn:
        name: comment_id
        referencedColumnName: comment_ID