Hypebeast\WordpressBundle\Entity\PostMeta:
  type: entity
  table: wp_postmeta
  id:
    meta_id:
      type: bigint
      length: 20
      nullable: false
      generator: { strategy: AUTO }
  fields:
    meta_key:
      type: string
      length: 255
      nullable: true
    meta_value:
      type: text
      nullable: true
  manyToOne:
    post:
      targetEntity: Post
      inversedBy: metas
      joinColumn:
        name: post_id
        referencedColumnName: ID